/** Sample KOL directory for the wallet-tracker KOLs tab preview (test UI w/o DB). */
export type DemoKol = { name: string; handle: string; wallet: string };

export const DEMO_KOLS: DemoKol[] = [
  { name: 'dvces', handle: 'vibed333', wallet: 'BCag5vY2mNp8Lr3vQwEeThUiOoPaSdFgHjKUPJd' },
  { name: 'Ozark', handle: 'ohzarke', wallet: 'DZAa7fY2mNp8Lr3vQwEeThUiOoPaSdFgHjrXam' },
  { name: 'Cupsey', handle: 'cupseyy', wallet: 'suqh3vY2mNp8Lr3vQwEeThUiOoPaSdFgHQfK' },
  { name: 'Kadenox', handle: 'kadenox', wallet: '3pZ5nyyWEzpPPiWimP8vYm7sD7TD3LAtmsGj' },
  { name: '^1s1mple', handle: 's1mple_s1mple', wallet: 'AeLayfrKC8kZE3KNkrHERKzAetSxbrWePFe3' },
  { name: 'LilmoonLambo', handle: 'lilmoonlambo', wallet: 'GJyh6NFEcjBCtnNLFko2FqVQBq8HHM137W8B' },
  { name: 'Awkchan45', handle: 'awkchan45', wallet: '3LYtnyyWEzpPPiWimP8vYm7sD7TD3LAtkwPx' },
  { name: 'Til', handle: 'tilcrypto', wallet: 'EHg5yfrKC8kZE3KNkrHERKzAetSxbrWeMyaf' },
  { name: 'Danny', handle: '0xsevere', wallet: '9FNzxgHyF7AeE6TZkSmFsko444wqoP15i138r' },
  { name: 'Gh0stee', handle: 'gh0stee', wallet: '2kv8NFEcjBCtnNLFko2FqVQBq8HHM13kRva9' },
  { name: 'Insentos', handle: 'insentos', wallet: '7SDsyfrKC8kZE3KNkrHERKzAetSxbrWeseHS' },
  { name: 'Beaver', handle: 'beaverd', wallet: 'GM7HxgHyF7AeE6TZkSmFsko444wqoP15i8NvN' },
  { name: 'Cxltures', handle: 'cxlturesvz', wallet: '3ZtwnyyWEzpPPiWimP8vYm7sD7TD3LAtqnAJ' },
  { name: 'Dan176', handle: '176dan', wallet: 'J2B5yfrKC8kZE3KNkrHERKzAetSxbrWeoaGM' },
  { name: 'Lynk', handle: 'lynk0x', wallet: 'CkPFxgHyF7AeE6TZkSmFsko444wqoP15iu7xD' },
  { name: 'Cented', handle: 'cented7', wallet: 'CyaE1VxvBrahnPWkqm5VsdCvyS2QmNhta54o' },
  { name: 'Jalen', handle: 'ripjalens', wallet: 'F72vnyyWEzpPPiWimP8vYm7sD7TD3LAtw6qL' },
  { name: '404Flipped', handle: '404flipped', wallet: 'AbcXyfrKC8kZE3KNkrHERKzAetSxbrWeBbcE' },
  { name: 'cladz', handle: 'cladzsol', wallet: 'EaVbyfrKC8kZE3KNkrHERKzAetSxbrWeS2kK' },
  { name: 'Solstice', handle: 'the__solstice', wallet: 'GrD2nyyWEzpPPiWimP8vYm7sD7TD3LAteaDN' },
  { name: 'Absol', handle: 'absolquant', wallet: 'BXNiyfrKC8kZE3KNkrHERKzAetSxbrWeSLWN' },
  { name: 'Dali', handle: 'solanadali', wallet: 'CvNiyfrKC8kZE3KNkrHERKzAetSxbrWek5mB' },
  { name: 'QTDEGEN', handle: 'qtdegen', wallet: '7tiRxgHyF7AeE6TZkSmFsko444wqoP15i6RLA' },
  { name: 'ducky', handle: 'zxduckyxyz', wallet: 'ADC1yfrKC8kZE3KNkrHERKzAetSxbrWeA2ph' },
  { name: 'LevanSolana', handle: 'levaninsolana', wallet: '5V9zyfrKC8kZE3KNkrHERKzAetSxbrWeQXNL' },
  { name: 'Leens', handle: 'leensx100', wallet: '7labyfrKC8kZE3KNkrHERKzAetSxbrWeP4CY' },
  { name: 'GVQ', handle: 'gvq_xx', wallet: 'GVQtyfrKC8kZE3KNkrHERKzAetSxbrWejMkF' },
  { name: 'Bandit', handle: 'bandeeeez', wallet: '5B79yfrKC8kZE3KNkrHERKzAetSxbrWe9q2X' },
  { name: 'Gr3g', handle: 'gr3gor14n', wallet: 'J23qyfrKC8kZE3KNkrHERKzAetSxbrWe7wsA' },
  { name: 'Jack Duval', handle: 'jackduvalstocks', wallet: 'BAr5yfrKC8kZE3KNkrHERKzAetSxbrWeXJPh' },
  { name: 'Betman', handle: 'imthebetman', wallet: 'BoYHyfrKC8kZE3KNkrHERKzAetSxbrWebcGG' },
  { name: 'Aloh', handle: 'alohquant', wallet: 'xXpRyfrKC8kZE3KNkrHERKzAetSxbrWehHQh' },
  { name: 'Spike', handle: 'notspikey', wallet: 'FhsSyfrKC8kZE3KNkrHERKzAetSxbrWe718z' },
  { name: 'Colercooks', handle: 'colercooks', wallet: '99xnyfrKC8kZE3KNkrHERKzAetSxbrWeLXrs' },
  { name: 'Zuki', handle: 'zukiweb3', wallet: '922VyfrKC8kZE3KNkrHERKzAetSxbrWeygrG' },
  { name: 'Ramset', handle: 'ramsetx', wallet: '71PCyfrKC8kZE3KNkrHERKzAetSxbrWe9UtQ' },
  { name: 'Grimace', handle: 'naughtygrimace', wallet: 'EA4MyfrKC8kZE3KNkrHERKzAetSxbrWeMBJr' },
  { name: 't9ndra', handle: 't9ndra', wallet: '3UNPyfrKC8kZE3KNkrHERKzAetSxbrWeX3n3' },
  { name: 'Trenchman', handle: 'trenchmanjames', wallet: 'Hw5UyfrKC8kZE3KNkrHERKzAetSxbrWeXoc7' },
  { name: 'iceman', handle: '77aez', wallet: 'DVMkyfrKC8kZE3KNkrHERKzAetSxbrWe7Mff' },
  { name: 'Inside Calls', handle: 'insidecalls', wallet: '4Ntyyfrkc8kZE3KNkrHERKzAetSxbrWeax9a' },
  { name: 'blu6k', handle: 'blu6k', wallet: '8Ltvyfrkc8kZE3KNkrHERKzAetSxbrWeu6YP' },
  { name: 'Stigman', handle: 'stigman__', wallet: '8fsKyfrkc8kZE3KNkrHERKzAetSxbrWedJw4' },
  { name: 'whashywash', handle: 'whashywash', wallet: 'GZVSyfrkc8kZE3KNkrHERKzAetSxbrWeLM9b' },
  { name: 'Clown', handle: 'clowntrenches', wallet: 'EDXHyfrkc8kZE3KNkrHERKzAetSxbrWe8HR8' },
];
